name: bedsheet_calc
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_masked_text: ^0.7.0
  cupertino_icons: ^0.1.2
  flutter_cupertino_date_picker: ^1.0.11
  intl: ^0.15.7
  http: ^0.12.0+2
  shared_preferences: ^0.4.3
  image_picker: 0.6.2+1
  mime: ^0.9.6+3
  toast: ^0.1.5
  custom_progress_dialog: ^1.0.3
  url_launcher: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_icons:
  android: true
  ios: true
  image_path:
    - assets/square.JPG

flutter:
  uses-material-design: true
  assets:
    - assets/images/